tree_menu/categories/urls.py
from django.urls import path

from .views import category_posts, index

app_name = "menu"


urlpatterns = [
    path("", index, name="index"),
    path("categories/<int:cat_id>/", category_posts, name="category"),
]

tree_menu/tree_menu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("categories.urls", namespace="menu")),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATICFILES_DIRS
    )

tree_menu/categories/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=50,
                             verbose_name="Наименование")
    super_category = models.ForeignKey('self',
                                       on_delete=models.PROTECT,
                                       verbose_name="Надкатегория",
                                       related_name="subs",
                                       null=True,
                                       blank=True)

    def __str__(self):
        if self.super_category:
            return "{} - {}".format(self.super_category.title, self.title)
        return self.title

    def count_subs(self):
        return self.subs.count()

    count_subs.short_description = "Кол-во вложенных категорий"

    class Meta:
        ordering = ("super_category__title", "title")
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

tree_menu/categories/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category


def index(request):
    context = {"cat_id": None}
    return render(request, "index.html", context)


def category_posts(request, cat_id):
    cat = Category.objects.get(pk=cat_id)
    context = {
        "cat": cat,
        "cat_id": cat_id
    }
    template_name = "category.html"
    return render(request, template_name, context)

tree_menu/templates/base.html
<!DOCTYPE html>
{% load filter_active %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Главная{% endblock title %}</title>
    <link rel="stylesheet" href="{% static "menu/style.css" %}">
</head>
<body>
    <ul>
        <li><a href="{% url "menu:index" %}">Главная</a></li>
        {% enclosure_menu cat_id %}
    </ul>
    {% block content %}{% endblock content %}
</body>
</html>

tree_menu/templates/category.html
{% extends "base.html" %}

{% block title %}
    {{ cat.title }}
{% endblock  %}

{% block content %}
    <p>{{ cat.title }} - {{ cat.count_subs }}</p>
{% endblock content %}

tree_menu/templates/include/active_cat.html
{% load filter_active %}
    {% for super_cat in super_cats %}
        <li>
            <a {% if cat == super_cat %} class="active_category" {% endif %} href="{% url "menu:category" super_cat.id %}">
                {{ super_cat.title }}
            </a>
        </li>
        {% if cat == super_cat %}
            {% include "include/sub_categories.html" %}
        {% elif cat.super_category == super_cat %}
            <ul>
                <li>
                    <a class="active_category" href="{% url "menu:category" cat_id %}">
                        {{ cat.title }}
                    </a>
                </li>
                {% include "include/sub_categories.html" %}
            </ul>
        {% endif %}
    {% endfor %}

tree_menu/templates/include/sub_categories.html
                <ul>
                    {% for sub in subs %}
                        <li>
                            <a href="{% url "menu:category" sub.id %}">
                                {{ sub.title }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>

tree_menu/templates/index.html
{% extends "base.html" %}

{% block content %}
    Главная страница
{% endblock content %}